# Generated by Django 2.2.9 on 2022-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo_status',
            field=models.DecimalField(auto_created=True, decimal_places=0, max_digits=3),
        ),
    ]
